#!/usr/bin/env bash
### dapp-create -- deploy a compiled contract (--verify on Etherscan)
### Usage: dapp create <name>
### Add --verify and export your ETHERSCAN_API_KEY to auto-verify on Etherscan
set -e
for i in "$@"; do
  case $i in
    --verify)
      DAPP_VERIFY_CONTRACT=yes
      shift
      ;;
    *)
      shift
      set -- "$@" "$i"
      ;;
  esac
done

mapfile -t contracts < <(<"$DAPP_JSON" jq '.contracts|keys[]' -r)

for path in "${contracts[@]}"; do
  [[ "${path#*:}" = "$1" ]] && {
    name="$path"
    break
  }
done

[[ "$name" ]] || exit 1 # not found

data=$(<"$DAPP_JSON" jq '.contracts' -r)
contract=$(echo "$data" | jq '.[''"'"$path"'"'']')
abi=$(jq '.["abi"]' -r <<< "$contract")
bin=$(jq '.["bin"]' -r <<< "$contract")
type=$(seth --abi-constructor <<< "$abi")
address=$(set -x; seth send --create "$bin" "${type/constructor/${1##*/}}" "${@:2}")

[[ $DAPP_VERIFY_CONTRACT ]] && {
  echo >&2 "Verifying contract at $address"
  path=$(sed 's|\/|/|g' "$DAPP_JSON" | sed "s/.*\"\(.*:${1}\)\".*/\1/g")
  sleep 5
  dapp verify-contract "$path" "$address" || true
}

echo "$address"
